# Generated by Django 4.2.3 on 2023-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_checkers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='current_turn',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black')], default='white', max_length=5),
        ),
    ]
