# Generated by Django 4.2.3 on 2023-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkers',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
