# Generated by Django 4.2.3 on 2023-07-22 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_checkers_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkers',
            unique_together={('row', 'column')},
        ),
    ]
