# Generated by Django 4.2.3 on 2023-07-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_checkers_captured'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkers',
            name='on_board',
            field=models.BooleanField(default=True),
        ),
    ]
