# Generated by Django 4.2.3 on 2023-07-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_checkers_on_board'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkers',
            unique_together={('row', 'column', 'captured')},
        ),
    ]
